#!/bin/bash

mkdir -p .build-tmp
find src -name '*.js' \
  | grep -v '[Mm]ain.js' \
  | xargs cat \
  | tee .build-tmp/verse.js .build-tmp/test.js >/dev/null

cat src/main.js     >> .build-tmp/verse.js

find test -name '*.js' \
  | xargs cat \
  >> .build-tmp/test.js

jasmine .build-tmp/test.js

